# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

app_home:
    path: /
    controller: App\Controller\Public\HomeController::index

app_login:
    path: /login
    controller: App\Security\SecurityController::login

app_logout:
    path: /logout
    methods: GET

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
